#!/usr/bin/env python3
"""Generate CATALOG.md from catalog.json."""

import json
import sys
from collections import defaultdict
from pathlib import Path

ROOT = Path(__file__).parent.parent
CATALOG = ROOT / "catalog.json"
OUTPUT = ROOT / "CATALOG.md"

SECTION_DESCRIPTIONS = {
    "ai": ("AI/LLM workloads", "LLM serving, vector DBs, PII detection, AI gateway dependencies"),
    "apps": ("Sample workloads", "Demo apps (whoami, httpbin) across platforms"),
    "compute": ("Clusters & VMs", "Managed Kubernetes and IaaS per cloud provider"),
    "observability": ("Metrics, logs, traces", "Grafana, Prometheus, Loki, Tempo, Langfuse, OpenTelemetry"),
    "security": ("Identity providers", "Cognito, EntraID, Keycloak, OCI instance principal"),
    "tools": ("Cluster add-ons", "ArgoCD, cert-manager, PostgreSQL, Redis, k6, MCP inspector"),
    "traefik": ("Traefik Hub installs", "Traefik Hub across every platform — always included in every PoC"),
}

COMMON_STACKS = [
    {
        "use_case": "AWS — API management + SSO + observability",
        "modules": [
            "terraform/compute/aws/eks",
            "terraform/traefik/shared",
            "terraform/traefik/k8s",
            "terraform/security/cognito",
            "terraform/observability/grafana-stack/k8s",
        ],
        "charts": ["helm/airlines"],
        "notes": "Full API portal with Cognito auth and Grafana metrics/logs.",
    },
    {
        "use_case": "Azure — AI chatbot + PII masking (HIPAA)",
        "modules": [
            "terraform/compute/azure/aks",
            "terraform/traefik/shared",
            "terraform/traefik/k8s",
            "terraform/security/entraid",
            "terraform/ai/ollama/k8s",
            "terraform/ai/presidio/k8s",
            "terraform/ai/open-webui/k8s",
            "terraform/observability/langfuse/k8s",
        ],
        "charts": [],
        "notes": "CPU LLM with PII scrubbing before model, EntraID OIDC, LLM tracing.",
    },
    {
        "use_case": "GCP — MCP gateway for internal AI agents",
        "modules": [
            "terraform/compute/gcp/gke",
            "terraform/traefik/shared",
            "terraform/traefik/k8s",
            "terraform/security/keycloak/k8s",
            "terraform/ai/ai-gateway-dependencies/k8s",
            "terraform/tools/mcp-inspector/k8s",
            "terraform/apps/httpbin/k8s",
            "terraform/apps/whoami/k8s",
        ],
        "charts": [],
        "notes": "MCP gateway with per-agent authz, Keycloak IdP, MCP inspector for debugging.",
    },
    {
        "use_case": "Local (k3d) — quick dev demo",
        "modules": [
            "terraform/compute/suse/k3d",
            "terraform/traefik/shared",
            "terraform/traefik/k8s",
        ],
        "charts": ["helm/airlines"],
        "notes": "No cloud account needed. Fastest path to a running demo.",
    },
]


def fmt_required(inputs: list) -> str:
    if not inputs:
        return "*(none)*"
    return ", ".join(f"`{i['name']}`" for i in inputs)


def fmt_keywords(kws: list) -> str:
    if not kws:
        return ""
    return ", ".join(f"`{k}`" for k in kws[:6])


def generate(data: dict) -> str:
    modules = data["modules"]
    charts = data["charts"]

    by_section: dict[str, list] = defaultdict(list)
    for m in modules:
        by_section[m["section"]].append(m)

    lines = []

    lines += [
        "# Demo Catalog",
        "",
        "> Auto-generated by `make catalog-markdown`. Do not edit by hand — run `make catalog-markdown` to refresh.",
        "> Source of truth: [`catalog.json`](./catalog.json) (regenerated by `make catalog`).",
        "",
    ]

    # ── Sections at a glance ──────────────────────────────────────────────────
    lines += ["## Sections at a glance", ""]
    lines += ["| Section | Modules | Use when | What belongs here |"]
    lines += ["|---|---|---|---|"]
    for section in sorted(by_section):
        count = len(by_section[section])
        use_when, what = SECTION_DESCRIPTIONS.get(section, ("—", "—"))
        lines.append(f"| `{section}` | {count} | {use_when} | {what} |")
    lines += ["", f"Total: **{len(modules)} modules**, **{len(charts)} Helm charts**", ""]

    # ── Module index ──────────────────────────────────────────────────────────
    lines += ["## Module index", ""]

    for section in sorted(by_section):
        lines += [f"### {section}", ""]
        lines += ["| Path | Required inputs | Keywords |"]
        lines += ["|---|---|---|"]
        for m in sorted(by_section[section], key=lambda x: x["path"]):
            req = fmt_required(m.get("required_inputs", []))
            kw = fmt_keywords(m.get("keywords", []))
            desc = m.get("description", "").split(".")[0]  # first sentence
            lines.append(f"| [`{m['path']}`](./{m['path']}) | {req} | {kw} |")
        lines.append("")
        # descriptions as a separate block for readability
        for m in sorted(by_section[section], key=lambda x: x["path"]):
            desc = m.get("description", "").split(".")[0]
            if desc:
                lines.append(f"- **{m['name']}** (`{m['platform']}`): {desc}.")
        lines.append("")

    # ── Helm charts ───────────────────────────────────────────────────────────
    lines += ["## Helm charts", ""]
    lines += ["| Chart | Required values | Dependencies | Keywords |"]
    lines += ["|---|---|---|---|"]
    for c in sorted(charts, key=lambda x: x["name"]):
        req = ", ".join(f"`{v}`" for v in c.get("required_values", [])) or "*(none)*"
        deps = ", ".join(f"`{d}`" for d in c.get("dependencies", [])) or "*(none)*"
        kw = fmt_keywords(c.get("keywords", []))
        lines.append(f"| [`{c['path']}`](./{c['path']}) | {req} | {deps} | {kw} |")
    lines.append("")

    # umbrella note
    lines += [
        "> **Umbrella charts**: `helm/airlines` and `helm/ai-gateway` bundle their subcharts.",
        "> If you install an umbrella, do NOT also install its subcharts standalone.",
        "> Gate sub-features via `enabled: true|false` in `values.yaml`.",
        "",
    ]

    # ── Common PoC stacks ─────────────────────────────────────────────────────
    lines += ["## Common PoC stacks", ""]
    lines += [
        "Starting points for common prospect patterns.",
        "Always add `terraform/traefik/shared` — it is required for every PoC.",
        "",
    ]
    for stack in COMMON_STACKS:
        lines.append(f"### {stack['use_case']}")
        lines.append("")
        if stack["notes"]:
            lines.append(f"{stack['notes']}")
            lines.append("")
        lines.append("**Modules:**")
        for m in stack["modules"]:
            lines.append(f"- `{m}`")
        if stack["charts"]:
            lines.append("")
            lines.append("**Charts:**")
            for c in stack["charts"]:
                lines.append(f"- `{c}`")
        lines.append("")

    # ── Footer ────────────────────────────────────────────────────────────────
    lines += [
        "---",
        "",
        "## Adding to the catalog",
        "",
        "New modules and charts appear automatically after `make catalog` is run.",
        "Update [`signals.yaml`](./signals.yaml) to add extra synonym keywords for new entries.",
        "CI fails if `catalog.json` drifts from the tree — run `make catalog` before committing.",
        "",
    ]

    return "\n".join(lines) + "\n"


def main():
    if not CATALOG.exists():
        print(f"ERROR: {CATALOG} not found. Run `make catalog` first.", file=sys.stderr)
        sys.exit(1)

    with open(CATALOG) as f:
        data = json.load(f)

    content = generate(data)

    if "--check" in sys.argv:
        if OUTPUT.exists():
            existing = OUTPUT.read_text()
            if existing == content:
                print("CATALOG.md: in sync")
                sys.exit(0)
            else:
                print("CATALOG.md is stale. Run `make catalog-markdown` and commit the result.", file=sys.stderr)
                sys.exit(1)
        else:
            print("CATALOG.md does not exist. Run `make catalog-markdown` first.", file=sys.stderr)
            sys.exit(1)

    OUTPUT.write_text(content)
    print(f"CATALOG.md generated ({len(content.splitlines())} lines)")


if __name__ == "__main__":
    main()
